# Generated by Django 5.2.17 on 2026-08-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_categoria_options_alter_categoria_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
