# Generated by Django 5.2.17 on 2026-08-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_produto_descricao_produto_descricao_detalhada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao_detalhada',
        ),
        migrations.AlterField(
            model_name='produto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='produtos/videos/'),
        ),
    ]
